### ISSUE TITLE
enhancement - ui eye candy

### ISSUE THREAD

**Issue by johndpope** [adamwaite/CoinBar#11]
http://cryptoconstruct.com/
<img width="1107" alt="screen shot 2017-10-02 at 2 25 59 pm" src="https://user-images.githubusercontent.com/289994/31092841-b70864dc-a77d-11e7-8736-3a795fa17573.png">

maybe able to re-use this code for plug and play
https://github.com/danielgindi/Charts

source code
https://github.com/SoftwareSyndicate/Construct

**Comment by johndpope** [comment]
of course - it would have to be a translucent black ui theme for it to earn status in dock. 
like little snitch

<img width="516" alt="screen shot 2017-10-02 at 2 36 16 pm" src="https://user-images.githubusercontent.com/289994/31093239-155308ac-a77f-11e7-9b5c-af98fed39de0.png">

**Comment by johndpope** [comment]
closer to this / though the blue graph needs to be white 
<img width="811" alt="screen shot 2017-10-02 at 2 48 42 pm" src="https://user-images.githubusercontent.com/289994/31093783-d47efbae-a780-11e7-8568-64a32f780870.png">

**Comment by johndpope** [comment]
I can prototype this on a branch - @adamwaite - any preference to carthage / cocoapods or SPM?

**Comment by johndpope** [comment]
I threw this together
https://github.com/johndpope/CoinBar/tree/charts

<img width="490" alt="screen shot 2017-10-03 at 11 40 33 am" src="https://user-images.githubusercontent.com/289994/31134428-093483b4-a830-11e7-9767-297bb3556e12.png">

will circle back when have more time.

**Comment by adamwaite** [comment]
Wow this is really cool. Is that your design in the second comment? That would be awesome.

**Comment by johndpope** [comment]
hi @adamwaite 

I'm thinking - 
one top graph (or bottom one) would suffice -
 then on hover in smaller list - then update data.
trying to use http://cryptoconstruct.com/ is painfully slow on latest iphone.
desktop is fine. 
black design is inspired by little snitch.

![jud1p](https://user-images.githubusercontent.com/289994/31313581-f2eab546-abb4-11e7-8a53-bd4652a253c6.png)
