### ISSUE TITLE
Program is unresponsive

### ISSUE THREAD

**Issue by zsiglin** [adamwaite/CoinBar#3]
2017 MBP w/Touch Bar running High Sierra 17A365. 

The program's icon appears in the menu bar, but is otherwise completely unresponsive. Compiled from source with same result.

**Comment by zsiglin** [comment]
My Swift knowledge is next to none, but after some rudimentary debugging it seems to be having issues pulling data down from the coinmarketcap.com API. (Maybe an SSL issue).

[BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length

**Comment by tysonwil** [comment]
Yeah looks to be a SSL issue

**Comment by adamwaite** [comment]
I think this is the problem - on it https://github.com/adamwaite/CoinBar/issues/9

**Comment by adamwaite** [comment]
Fixed in release 1.0.1
