### ISSUE TITLE
Background color isn't correct

### ISSUE THREAD

**Issue by tysonwil** [adamwaite/CoinBar#5]
<img width="262" alt="screen shot 2017-09-25 at 11 36 02 pm" src="https://user-images.githubusercontent.com/1772767/30845961-87875eb2-a24a-11e7-93a9-ea9d0067ae30.png">

**Comment by adamwaite** [comment]
Fixed in release 1.0.1

**Comment by adamwaite** [comment]
Still unhappy with the way it looks on light themes.

**Comment by adamwaite** [comment]
Fixed on 1.1
